//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aksesuar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aksesuar()
        {
            this.aksesuarDeger = new HashSet<aksesuarDeger>();
            this.DigerDokumanlar = new HashSet<DigerDokumanlar>();
            this.FiyatListesi = new HashSet<FiyatListesi>();
            this.Fotograflar = new HashSet<Fotograflar>();
            this.KaliteDokumanlari = new HashSet<KaliteDokumanlari>();
            this.Kataloglar = new HashSet<Kataloglar>();
            this.MontajKlavuzlari = new HashSet<MontajKlavuzlari>();
            this.Sertifikalar = new HashSet<Sertifikalar>();
            this.Taglar = new HashSet<Taglar>();
            this.TeknikCizimler = new HashSet<TeknikCizimler>();
            this.TeknikSartname = new HashSet<TeknikSartname>();
            this.UretimDokumanlari = new HashSet<UretimDokumanlari>();
            this.Urunlerurunler_Aksesuaraksesuar = new HashSet<Urunlerurunler_Aksesuaraksesuar>();
            this.WebFotograf = new HashSet<WebFotograf>();
        }
    
        public System.Guid Oid { get; set; }
        public string AksesuarAdi { get; set; }
        public string AksesuarKodu { get; set; }
        public Nullable<System.Guid> yukseklik { get; set; }
        public Nullable<System.Guid> boyut { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<System.Guid> AksesuarGrubu { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<System.Guid> urunGrubu { get; set; }
        public Nullable<System.Guid> urunSerisi { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public Nullable<System.Guid> urunAilesi { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string Aciklama { get; set; }
        public string EngAksesuarAdi { get; set; }
        public string EngAciklama { get; set; }
        public Nullable<bool> EngWeb { get; set; }
        public string StokKodu { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public string C_AksesuarAdi { get; set; }
        public string WebUrl { get; set; }
        public string EngWebUrl { get; set; }
    
        public virtual AksesuarGrubu AksesuarGrubu1 { get; set; }
        public virtual Boyut Boyut1 { get; set; }
        public virtual UrunAilesi UrunAilesi1 { get; set; }
        public virtual UrunGrubu UrunGrubu1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
        public virtual UrunSerisi UrunSerisi1 { get; set; }
        public virtual Yukseklik Yukseklik1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aksesuarDeger> aksesuarDeger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigerDokumanlar> DigerDokumanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiyatListesi> FiyatListesi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotograflar> Fotograflar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KaliteDokumanlari> KaliteDokumanlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kataloglar> Kataloglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MontajKlavuzlari> MontajKlavuzlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sertifikalar> Sertifikalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taglar> Taglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeknikCizimler> TeknikCizimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeknikSartname> TeknikSartname { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimDokumanlari> UretimDokumanlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunlerurunler_Aksesuaraksesuar> Urunlerurunler_Aksesuaraksesuar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebFotograf> WebFotograf { get; set; }
    }
}
