//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditDataItemPersistent
    {
        public System.Guid Oid { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string OperationType { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> AuditedObject { get; set; }
        public Nullable<System.Guid> OldObject { get; set; }
        public Nullable<System.Guid> NewObject { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual AuditedObjectWeakReference AuditedObjectWeakReference { get; set; }
        public virtual XPWeakReference XPWeakReference { get; set; }
        public virtual XPWeakReference XPWeakReference1 { get; set; }
    }
}
