//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditedObjectWeakReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditedObjectWeakReference()
        {
            this.AuditDataItemPersistent = new HashSet<AuditDataItemPersistent>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> GuidId { get; set; }
        public Nullable<int> IntId { get; set; }
        public string DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistent { get; set; }
        public virtual XPWeakReference XPWeakReference { get; set; }
    }
}
