//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degerler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Degerler()
        {
            this.aksesuarDeger = new HashSet<aksesuarDeger>();
            this.UrunDegerler = new HashSet<UrunDegerler>();
        }
    
        public System.Guid Oid { get; set; }
        public string DegerAdi { get; set; }
        public string Deger { get; set; }
        public Nullable<System.Guid> DegerTipi { get; set; }
        public Nullable<System.Guid> ozellikler { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string EngDegerAdi { get; set; }
        public Nullable<bool> EngWeb { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aksesuarDeger> aksesuarDeger { get; set; }
        public virtual DegerTipleri DegerTipleri { get; set; }
        public virtual Ozellikler Ozellikler1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunDegerler> UrunDegerler { get; set; }
    }
}
