//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiyatListesi
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> File { get; set; }
        public Nullable<double> ListeFiyati { get; set; }
        public Nullable<System.Guid> Currency { get; set; }
        public Nullable<System.Guid> aksesuar { get; set; }
        public Nullable<System.Guid> parcalar { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public string DokumanAdi { get; set; }
        public string dokumanUzanti { get; set; }
        public Nullable<int> DokumanType { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.Guid> fileData { get; set; }
    
        public virtual Aksesuar Aksesuar1 { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual FileData FileData1 { get; set; }
        public virtual FileData FileData2 { get; set; }
        public virtual Parcalar Parcalar1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
    }
}
