//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotograflar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fotograflar()
        {
            this.Revizeler = new HashSet<Revizeler>();
            this.Taglar = new HashSet<Taglar>();
            this.WebFotograf = new HashSet<WebFotograf>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> aksesuar { get; set; }
        public Nullable<System.Guid> kapakOpsiyonlari { get; set; }
        public Nullable<System.Guid> parcalar { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<System.Guid> urunAilesi { get; set; }
        public Nullable<System.Guid> urunGrubu { get; set; }
        public Nullable<System.Guid> urunSerisi { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public byte[] fotograf { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.Guid> File { get; set; }
        public string Content { get; set; }
        public Nullable<bool> EngWeb { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public Nullable<bool> KayitKontrol { get; set; }
        public Nullable<bool> EditKontrol { get; set; }
    
        public virtual Aksesuar Aksesuar1 { get; set; }
        public virtual FileData FileData { get; set; }
        public virtual KapakOpsiyonlari KapakOpsiyonlari1 { get; set; }
        public virtual Parcalar Parcalar1 { get; set; }
        public virtual UrunAilesi UrunAilesi1 { get; set; }
        public virtual UrunGrubu UrunGrubu1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
        public virtual UrunSerisi UrunSerisi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revizeler> Revizeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taglar> Taglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebFotograf> WebFotograf { get; set; }
    }
}
