//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HakkimizdaVeAltBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HakkimizdaVeAltBilgi()
        {
            this.HakkimizdaAltGrup = new HashSet<HakkimizdaAltGrup>();
            this.YonetimKadrosu = new HashSet<YonetimKadrosu>();
        }
    
        public System.Guid Oid { get; set; }
        public string AltBilgi { get; set; }
        public string HakkimizdaBaslk { get; set; }
        public string HakkimizdaAciklama { get; set; }
        public string HakkimizdaBaslk2 { get; set; }
        public string HakkimizdaAciklama2 { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string EngAltBilgi { get; set; }
        public string EngHakkimizdaBaslk { get; set; }
        public string EngHakkimizdaAciklama { get; set; }
        public string EngHakkimizdaBaslk2 { get; set; }
        public string EngHakkimizdaAciklama2 { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public byte[] fotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HakkimizdaAltGrup> HakkimizdaAltGrup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YonetimKadrosu> YonetimKadrosu { get; set; }
    }
}
