//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IK_VizyonPolitika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IK_VizyonPolitika()
        {
            this.Banner = new HashSet<Banner>();
        }
    
        public System.Guid Oid { get; set; }
        public string Baslik { get; set; }
        public string Vizyonumuz { get; set; }
        public string Politikamiz { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string EngBaslik { get; set; }
        public string EngVizyonumuz { get; set; }
        public string EngPolitikamiz { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banner { get; set; }
    }
}
