//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public System.Guid Oid { get; set; }
        public string IstTelefon { get; set; }
        public string IstFax { get; set; }
        public string IstAdres { get; set; }
        public string EskTelefon { get; set; }
        public string EskFax { get; set; }
        public string EskAdres { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
    }
}
