//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kataloglar
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> File { get; set; }
        public string KatalogAdi { get; set; }
        public Nullable<System.Guid> urunAilesi { get; set; }
        public Nullable<System.Guid> urunGrubu { get; set; }
        public Nullable<System.Guid> urunSerisi { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public byte[] fotograf { get; set; }
        public string WebDokumanAdi { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<bool> EngWeb { get; set; }
        public string EngWebDokumanAdi { get; set; }
        public Nullable<bool> LandeGenelKatalog { get; set; }
        public Nullable<bool> EngLandeGenelKatalog { get; set; }
        public Nullable<bool> KataloglarSayfasi { get; set; }
        public Nullable<int> index { get; set; }
        public Nullable<System.Guid> kataloglarSayfa { get; set; }
        public Nullable<bool> LKLK { get; set; }
        public Nullable<bool> EngLKLK { get; set; }
        public Nullable<System.Guid> Aksesuar { get; set; }
        public Nullable<System.Guid> aksesuarGrubu { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public string WebUrl { get; set; }
        public string EngWebUrl { get; set; }
    
        public virtual Aksesuar Aksesuar1 { get; set; }
        public virtual AksesuarGrubu AksesuarGrubu1 { get; set; }
        public virtual FileData FileData { get; set; }
        public virtual KataloglarSayfasi KataloglarSayfasi1 { get; set; }
        public virtual UrunAilesi UrunAilesi1 { get; set; }
        public virtual UrunGrubu UrunGrubu1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
        public virtual UrunSerisi UrunSerisi1 { get; set; }
    }
}
