//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasorler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klasorler()
        {
            this.KlasorDokumanlari = new HashSet<KlasorDokumanlari>();
            this.Klasorler1 = new HashSet<Klasorler>();
        }
    
        public System.Guid Oid { get; set; }
        public string KlasorAdi { get; set; }
        public string KlasorKodu { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<int> klasorTipiEnum { get; set; }
        public Nullable<System.Guid> parentKlasor { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string ParentKlasorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlasorDokumanlari> KlasorDokumanlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klasorler> Klasorler1 { get; set; }
        public virtual Klasorler Klasorler2 { get; set; }
    }
}
