//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurumsalLogoKullanimi
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> File { get; set; }
        public string Adi { get; set; }
        public string ENAdi { get; set; }
        public Nullable<System.Guid> Katalog { get; set; }
        public Nullable<System.Guid> ENKatalog { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual FileData FileData { get; set; }
        public virtual FileData FileData1 { get; set; }
        public virtual FileData FileData2 { get; set; }
    }
}
