//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnayBekleyenDokumanlar
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> File { get; set; }
        public Nullable<System.Guid> UserMid2 { get; set; }
        public Nullable<bool> red { get; set; }
        public string DokumanOlusturanKisi { get; set; }
        public Nullable<System.DateTime> DokumanOlusturulmaTarihi { get; set; }
        public Nullable<System.DateTime> DokumanOnaylanmaTarihi { get; set; }
        public Nullable<System.Guid> FileOid { get; set; }
        public Nullable<bool> onay { get; set; }
        public string ObjectType { get; set; }
        public Nullable<System.Guid> yetkilendirme { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string urunAilesi { get; set; }
        public string urunGrubu { get; set; }
        public string urunSerisi { get; set; }
        public string urunler { get; set; }
        public string OcrText { get; set; }
    
        public virtual FileData FileData { get; set; }
        public virtual UserMid2 UserMid21 { get; set; }
        public virtual Yetkilendirme Yetkilendirme1 { get; set; }
    }
}
