//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDescriptorPropertyDescriptors_PropertyBagDescriptorPropertyBags
    {
        public Nullable<System.Guid> PropertyBags { get; set; }
        public Nullable<System.Guid> PropertyDescriptors { get; set; }
        public System.Guid OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual PropertyBagDescriptor PropertyBagDescriptor { get; set; }
        public virtual PropertyDescriptor PropertyDescriptor { get; set; }
    }
}
