//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValue
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> Descriptor { get; set; }
        public Nullable<System.Guid> Bag { get; set; }
        public string StrValue { get; set; }
        public Nullable<System.Guid> WeakReference { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual PropertyBag PropertyBag { get; set; }
        public virtual PropertyDescriptor PropertyDescriptor { get; set; }
        public virtual XPWeakReference XPWeakReference { get; set; }
    }
}
