//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revizeler
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> teknikCizimler { get; set; }
        public Nullable<System.Guid> uretimDokumanlari { get; set; }
        public Nullable<System.Guid> fotograflar { get; set; }
        public Nullable<System.Guid> kaliteDokumanlari { get; set; }
        public Nullable<System.Guid> klasorDokumanlari { get; set; }
        public string RevizeEdenKisi { get; set; }
        public string RevizeNedeni { get; set; }
        public Nullable<System.Guid> RevizeDokuman { get; set; }
        public Nullable<System.Guid> YeniDokuman { get; set; }
        public Nullable<System.Guid> digerDokumanlar { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<System.Guid> MontajKlavuzlari { get; set; }
        public Nullable<System.DateTime> RevizeTarihi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.Guid> RevizeNedenleri { get; set; }
        public Nullable<System.Guid> sertifikaDoc { get; set; }
        public Nullable<System.Guid> sertifikaDokumanlari { get; set; }
        public Nullable<bool> MakineyeIslendi { get; set; }
        public Nullable<System.Guid> teknikSartname { get; set; }
    
        public virtual DigerDokumanlar DigerDokumanlar1 { get; set; }
        public virtual FileData FileData { get; set; }
        public virtual FileData FileData1 { get; set; }
        public virtual Fotograflar Fotograflar1 { get; set; }
        public virtual KaliteDokumanlari KaliteDokumanlari1 { get; set; }
        public virtual KlasorDokumanlari KlasorDokumanlari1 { get; set; }
        public virtual MontajKlavuzlari MontajKlavuzlari1 { get; set; }
        public virtual RevizeNedenleri RevizeNedenleri1 { get; set; }
        public virtual Sertifikalar Sertifikalar { get; set; }
        public virtual TeknikCizimler TeknikCizimler1 { get; set; }
        public virtual TeknikSartname TeknikSartname1 { get; set; }
        public virtual UretimDokumanlari UretimDokumanlari1 { get; set; }
    }
}
