//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taglar
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> urunAilesi { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public Nullable<System.Guid> aksesuar { get; set; }
        public Nullable<System.Guid> parcalar { get; set; }
        public Nullable<System.Guid> teknikCizimler { get; set; }
        public Nullable<System.Guid> uretimDokumanlari { get; set; }
        public Nullable<System.Guid> fotograflar { get; set; }
        public Nullable<System.Guid> kaliteDokumanlari { get; set; }
        public string Tag { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<System.Guid> digerDokumanlar { get; set; }
        public Nullable<System.Guid> kapakOpsiyonlari { get; set; }
        public Nullable<System.Guid> montajKlavuzlari { get; set; }
        public Nullable<System.Guid> klasorDokumanlari { get; set; }
        public Nullable<System.Guid> urunGrubu { get; set; }
        public Nullable<System.Guid> urunSerisi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.Guid> sertifikaDoc { get; set; }
        public Nullable<System.Guid> sertifikaDokumanlari { get; set; }
        public Nullable<System.Guid> teknikSartname { get; set; }
    
        public virtual Aksesuar Aksesuar1 { get; set; }
        public virtual DigerDokumanlar DigerDokumanlar1 { get; set; }
        public virtual Fotograflar Fotograflar1 { get; set; }
        public virtual KaliteDokumanlari KaliteDokumanlari1 { get; set; }
        public virtual KapakOpsiyonlari KapakOpsiyonlari1 { get; set; }
        public virtual KlasorDokumanlari KlasorDokumanlari1 { get; set; }
        public virtual MontajKlavuzlari MontajKlavuzlari1 { get; set; }
        public virtual Parcalar Parcalar1 { get; set; }
        public virtual Sertifikalar Sertifikalar { get; set; }
        public virtual TeknikCizimler TeknikCizimler1 { get; set; }
        public virtual TeknikSartname TeknikSartname1 { get; set; }
        public virtual UretimDokumanlari UretimDokumanlari1 { get; set; }
        public virtual UrunAilesi UrunAilesi1 { get; set; }
        public virtual UrunGrubu UrunGrubu1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
        public virtual UrunSerisi UrunSerisi1 { get; set; }
    }
}
