//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunGrubu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunGrubu()
        {
            this.Aksesuar = new HashSet<Aksesuar>();
            this.Banner = new HashSet<Banner>();
            this.DigerDokumanlar = new HashSet<DigerDokumanlar>();
            this.Fotograflar = new HashSet<Fotograflar>();
            this.KaliteDokumanlari = new HashSet<KaliteDokumanlari>();
            this.KapakOpsiyonlari = new HashSet<KapakOpsiyonlari>();
            this.Kataloglar = new HashSet<Kataloglar>();
            this.MontajKlavuzlari = new HashSet<MontajKlavuzlari>();
            this.Parcalar = new HashSet<Parcalar>();
            this.Sertifikalar = new HashSet<Sertifikalar>();
            this.Taglar = new HashSet<Taglar>();
            this.TeknikCizimler = new HashSet<TeknikCizimler>();
            this.TeknikSartname = new HashSet<TeknikSartname>();
            this.UretimDokumanlari = new HashSet<UretimDokumanlari>();
            this.Urunler = new HashSet<Urunler>();
            this.UrunSerisi = new HashSet<UrunSerisi>();
            this.WebFotograf = new HashSet<WebFotograf>();
        }
    
        public System.Guid Oid { get; set; }
        public string UrunGrubuAdi { get; set; }
        public Nullable<System.Guid> urunAilesi { get; set; }
        public string OlusturanKisi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string EngUrunGrubuAdi { get; set; }
        public string EngAciklama { get; set; }
        public Nullable<bool> EngWeb { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
        public string WebUrl { get; set; }
        public string EngWebUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aksesuar> Aksesuar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigerDokumanlar> DigerDokumanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotograflar> Fotograflar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KaliteDokumanlari> KaliteDokumanlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KapakOpsiyonlari> KapakOpsiyonlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kataloglar> Kataloglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MontajKlavuzlari> MontajKlavuzlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parcalar> Parcalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sertifikalar> Sertifikalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taglar> Taglar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeknikCizimler> TeknikCizimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeknikSartname> TeknikSartname { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimDokumanlari> UretimDokumanlari { get; set; }
        public virtual UrunAilesi UrunAilesi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunSerisi> UrunSerisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebFotograf> WebFotograf { get; set; }
    }
}
