//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_TeknikSartname
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> Urunler { get; set; }
        public Nullable<System.Guid> TeknikSarnameler { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual TeknikSartname TeknikSartname { get; set; }
        public virtual Urunler Urunler1 { get; set; }
    }
}
