//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunlerurunler_Aksesuaraksesuar
    {
        public Nullable<System.Guid> aksesuar { get; set; }
        public Nullable<System.Guid> urunler { get; set; }
        public System.Guid OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
    
        public virtual Aksesuar Aksesuar1 { get; set; }
        public virtual Urunler Urunler1 { get; set; }
    }
}
