//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserUsers_RoleRoles = new HashSet<UserUsers_RoleRoles>();
        }
    
        public System.Guid Oid { get; set; }
        public string StoredPassword { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> ChangePasswordOnFirstLogon { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUsers_RoleRoles> UserUsers_RoleRoles { get; set; }
    }
}
