//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUsers_RoleRoles
    {
        public Nullable<System.Guid> Roles { get; set; }
        public Nullable<System.Guid> Users { get; set; }
        public System.Guid OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
