//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMid2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMid2()
        {
            this.Departmanlar1 = new HashSet<Departmanlar>();
            this.OnayBekleyenDokumanlar = new HashSet<OnayBekleyenDokumanlar>();
            this.Yetkilendirme = new HashSet<Yetkilendirme>();
        }
    
        public System.Guid Oid { get; set; }
        public string AdiSoyadi { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public Nullable<System.Guid> departmanlar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departmanlar> Departmanlar1 { get; set; }
        public virtual Departmanlar Departmanlar2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnayBekleyenDokumanlar> OnayBekleyenDokumanlar { get; set; }
        public virtual PermissionPolicyUser PermissionPolicyUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yetkilendirme> Yetkilendirme { get; set; }
    }
}
