//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebFotograf
    {
        public System.Guid Oid { get; set; }
        public byte[] fotograf { get; set; }
        public Nullable<System.Guid> Urun { get; set; }
        public Nullable<System.Guid> UrunSerisi { get; set; }
        public Nullable<System.Guid> UrunGrubu { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<bool> Web { get; set; }
        public Nullable<bool> EngWeb { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.Guid> Aksesuar { get; set; }
        public Nullable<System.Guid> AksesuarGrubu { get; set; }
        public Nullable<System.Guid> KaliteliFotografOid { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
    
        public virtual Aksesuar Aksesuar1 { get; set; }
        public virtual AksesuarGrubu AksesuarGrubu1 { get; set; }
        public virtual Fotograflar Fotograflar { get; set; }
        public virtual UrunGrubu UrunGrubu1 { get; set; }
        public virtual Urunler Urunler { get; set; }
        public virtual UrunSerisi UrunSerisi1 { get; set; }
    }
}
