//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XpoState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XpoState()
        {
            this.XpoStateAppearance = new HashSet<XpoStateAppearance>();
            this.XpoStateMachine1 = new HashSet<XpoStateMachine>();
            this.XpoTransition = new HashSet<XpoTransition>();
            this.XpoTransition1 = new HashSet<XpoTransition>();
        }
    
        public System.Guid Oid { get; set; }
        public string Caption { get; set; }
        public Nullable<System.Guid> StateMachine { get; set; }
        public string MarkerValue { get; set; }
        public string TargetObjectCriteria { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual XpoStateMachine XpoStateMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XpoStateAppearance> XpoStateAppearance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XpoStateMachine> XpoStateMachine1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XpoTransition> XpoTransition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XpoTransition> XpoTransition1 { get; set; }
    }
}
