//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XpoStateAppearance
    {
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> State { get; set; }
        public string AppearanceItemType { get; set; }
        public string Context { get; set; }
        public string Criteria { get; set; }
        public string Method { get; set; }
        public string TargetItems { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> FontColor { get; set; }
        public Nullable<int> BackColor { get; set; }
        public Nullable<int> FontStyle { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> Visibility { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual XpoState XpoState { get; set; }
    }
}
