//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XpoTransition
    {
        public System.Guid Oid { get; set; }
        public string Caption { get; set; }
        public Nullable<System.Guid> SourceState { get; set; }
        public Nullable<System.Guid> TargetState { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> SaveAndCloseView { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual XpoState XpoState { get; set; }
        public virtual XpoState XpoState1 { get; set; }
    }
}
