//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XPWeakReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XPWeakReference()
        {
            this.AuditDataItemPersistent = new HashSet<AuditDataItemPersistent>();
            this.AuditDataItemPersistent1 = new HashSet<AuditDataItemPersistent>();
            this.PropertyValue = new HashSet<PropertyValue>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<int> TargetType { get; set; }
        public string TargetKey { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> ObjectType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditDataItemPersistent> AuditDataItemPersistent1 { get; set; }
        public virtual AuditedObjectWeakReference AuditedObjectWeakReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyValue> PropertyValue { get; set; }
        public virtual XPObjectType XPObjectType { get; set; }
        public virtual XPObjectType XPObjectType1 { get; set; }
    }
}
