//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XtraReportData
    {
        public int OID { get; set; }
        public string ObjectTypeName { get; set; }
        public byte[] Content { get; set; }
        public string Name { get; set; }
        public string ParametersObjectTypeName { get; set; }
        public Nullable<bool> IsInplaceReport { get; set; }
        public string PredefinedReportType { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    }
}
