//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetkilendirme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yetkilendirme()
        {
            this.OnayBekleyenDokumanlar = new HashSet<OnayBekleyenDokumanlar>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<System.Guid> departmanlar { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<System.Guid> yetkili { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Departmanlar Departmanlar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnayBekleyenDokumanlar> OnayBekleyenDokumanlar { get; set; }
        public virtual UserMid2 UserMid2 { get; set; }
    }
}
