//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandeWebProjectV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YoutubeVideo
    {
        public System.Guid Oid { get; set; }
        public string link { get; set; }
        public string aciklama { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string OlusturanKisi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string ResimLinki { get; set; }
        public string Value { get; set; }
        public Nullable<bool> AnasayfadaGoster { get; set; }
        public string EngAciklama { get; set; }
        public Nullable<System.Guid> videolarSayfasi { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<System.DateTime> SonGuncellemeTarihi { get; set; }
    
        public virtual VideolarSayfasi VideolarSayfasi1 { get; set; }
    }
}
